# Generated by Django 3.2.9 on 2021-11-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roche_api', '0002_auto_20211118_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='doctors', through='roche_api.PatientDoctorMembership', to='roche_api.Patient'),
        ),
    ]
